### ISSUE TITLE
Implementation of a use case

### ISSUE THREAD

**Issue by brunolnetto** [bshoshany/multithreaded-matrix#1]
I would like to implement the Runge-Kutta flavors with your library. It is required a matrix called Butcher's matrix. I was able to implement it well in [MatLab](https://github.com/asmovi/matlab-utils/blob/0b71a568d96030a6b334d1c932cba8047aa90a81/integrators/butcher_matrix.m), but for great degrees like 10, it is too slow. :-(  

May I use it?

**Comment by bshoshany** [comment]
Of course, you can use this library for whatever application you want! However, I'm not sure you will get any noticeable speedup for such small matrices. This library is mostly meant for matrices that have millions of elements.
